INSERT INTO disciplines VALUES (24, '100 metres Backstroke, Men');
INSERT INTO disciplines VALUES (15, '100 metres Breaststroke, Men');
INSERT INTO disciplines VALUES (14, '20 kilometres Race Walk, Men');
INSERT INTO disciplines VALUES (16, '200 metres Breaststroke, Men');
INSERT INTO disciplines VALUES (17, '4 × 100 metres Medley Relay, Men');
INSERT INTO disciplines VALUES (22, 'Balance Beam, Women');
INSERT INTO disciplines VALUES (9, 'Downhill, Men');
INSERT INTO disciplines VALUES (25, 'Featherweight, Freestyle, Women');
INSERT INTO disciplines VALUES (3, 'Floor Exercise, Men');
INSERT INTO disciplines VALUES (20, 'Floor Exercise, Women');
INSERT INTO disciplines VALUES (31, 'Foil, Individual, Men');
INSERT INTO disciplines VALUES (32, 'Foil, Team, Men');
INSERT INTO disciplines VALUES (10, 'Giant Slalom, Men');
INSERT INTO disciplines VALUES (6, 'Horizontal Bar, Men');
INSERT INTO disciplines VALUES (4, 'Horse Vault, Men');
INSERT INTO disciplines VALUES (23, 'Horse Vault, Women');
INSERT INTO disciplines VALUES (1, 'Individual All-Around, Men');
INSERT INTO disciplines VALUES (18, 'Individual All-Around, Women');
INSERT INTO disciplines VALUES (26, 'Individual, Men');
INSERT INTO disciplines VALUES (28, 'Individual, Open');
INSERT INTO disciplines VALUES (13, 'Lightweight, Freestyle, Women');
INSERT INTO disciplines VALUES (12, 'Middleweight, Freestyle, Women');
INSERT INTO disciplines VALUES (30, 'Open Class, Men');
INSERT INTO disciplines VALUES (5, 'Parallel Bars, Men');
INSERT INTO disciplines VALUES (8, 'Pommelled Horse, Men');
INSERT INTO disciplines VALUES (7, 'Rings, Men');
INSERT INTO disciplines VALUES (11, 'Slalom, Men');
INSERT INTO disciplines VALUES (2, 'Team All-Around, Men');
INSERT INTO disciplines VALUES (19, 'Team All-Around, Women');
INSERT INTO disciplines VALUES (27, 'Team, Men');
INSERT INTO disciplines VALUES (29, 'Team, Open');
INSERT INTO disciplines VALUES (21, 'Uneven Bars, Women');