INSERT INTO modality (id, name, sport) VALUES (1, 'Hockey Men''s Hockey', 'Hockey');
INSERT INTO modality (id, name, sport) VALUES (2, 'Athletics Men''s 3,000 metres Steeplechase', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (3, 'Wrestling Men''s Welterweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (4, 'Wrestling Men''s Middleweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (5, 'Swimming Men''s 50 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (6, 'Swimming Men''s 4 x 100 metres Freestyle Relay', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (7, 'Athletics Men''s Javelin Throw', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (8, 'Ice Hockey Men''s Ice Hockey', 'Ice Hockey');
INSERT INTO modality (id, name, sport) VALUES (9, 'Diving Women''s Platform', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (10, 'Fencing Men''s epee, Individual', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (11, 'Fencing Men''s epee, Team', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (12, 'Athletics Men''s Marathon', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (13, 'Athletics Men''s 20 kilometres Walk', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (14, 'Athletics Men''s 50 kilometres Walk', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (15, 'Archery Women''s Individual', 'Archery');
INSERT INTO modality (id, name, sport) VALUES (16, 'Shooting Men''s Skeet', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (17, 'Shooting Men''s Free Pistol, 50 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (18, 'Shooting Men''s Air Pistol, 10 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (19, 'Swimming Women''s 200 metres Backstroke', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (20, 'Swimming Men''s 400 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (21, 'Swimming Men''s 1,500 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (22, 'Swimming Men''s 4 x 200 metres Freestyle Relay', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (23, 'Football Men''s Football', 'Football');
INSERT INTO modality (id, name, sport) VALUES (24, 'Basketball Men''s Basketball', 'Basketball');
INSERT INTO modality (id, name, sport) VALUES (25, 'Rowing Men''s Coxed Eights', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (26, 'Cycling Men''s Team Pursuit, 4,000 metres', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (27, 'Cycling Men''s Madison', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (28, 'Wrestling Men''s Welterweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (29, 'Football Women''s Football', 'Football');
INSERT INTO modality (id, name, sport) VALUES (30, 'Rowing Women''s Coxed Eights', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (31, 'Volleyball Men''s Volleyball', 'Volleyball');
INSERT INTO modality (id, name, sport) VALUES (32, 'Swimming Women''s 100 metres Butterfly', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (33, 'Swimming Women''s 4 x 100 metres Medley Relay', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (34, 'Swimming Men''s 400 metres Individual Medley', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (35, 'Sailing Mixed Two Person Heavyweight Dinghy', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (36, 'Cycling Men''s Road Race, Individual', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (37, 'Cycling Men''s 100 kilometres Team Time Trial', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (38, 'Snowboarding Men''s Halfpipe', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (39, 'Cross Country Skiing Men''s 15 kilometres', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (40, 'Cross Country Skiing Men''s 30 kilometres', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (41, 'Cross Country Skiing Men''s 50 kilometres', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (42, 'Hockey Women''s Hockey', 'Hockey');
INSERT INTO modality (id, name, sport) VALUES (43, 'Rowing Men''s Coxed Fours', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (44, 'Gymnastics Women''s Individual All-Around', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (45, 'Gymnastics Women''s Floor Exercise', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (46, 'Gymnastics Women''s Horse Vault', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (47, 'Gymnastics Women''s Uneven Bars', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (48, 'Gymnastics Women''s Balance Beam', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (49, 'Gymnastics Women''s Team All-Around', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (50, 'Softball Women''s Softball', 'Softball');
INSERT INTO modality (id, name, sport) VALUES (51, 'Biathlon Men''s 10 kilometres Sprint', 'Biathlon');
INSERT INTO modality (id, name, sport) VALUES (52, 'Biathlon Men''s 20 kilometres', 'Biathlon');
INSERT INTO modality (id, name, sport) VALUES (53, 'Athletics Men''s 4 x 100 metres Relay', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (54, 'Alpine Skiing Women''s Giant Slalom', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (55, 'Alpine Skiing Women''s Slalom', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (56, 'Synchronized Swimming Women''s Team', 'Synchronized Swimming');
INSERT INTO modality (id, name, sport) VALUES (57, 'Synchronized Swimming Women''s Duet', 'Synchronized Swimming');
INSERT INTO modality (id, name, sport) VALUES (58, 'Equestrianism Mixed Jumping, Individual', 'Equestrianism');
INSERT INTO modality (id, name, sport) VALUES (59, 'Athletics Women''s 400 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (60, 'Athletics Women''s 800 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (61, 'Athletics Women''s 1,500 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (62, 'Athletics Men''s High Jump', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (63, 'Shooting Men''s Running Target, Single And Double Shot', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (64, 'Baseball Men''s Baseball', 'Baseball');
INSERT INTO modality (id, name, sport) VALUES (65, 'Rowing Men''s Coxless Fours', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (66, 'Sailing Mixed Two Person Keelboat', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (67, 'Sailing Mixed Three Person Keelboat', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (68, 'Swimming Men''s 200 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (69, 'Sailing Mixed Multihull', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (70, 'Athletics Women''s 5,000 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (71, 'Canoeing Men''s Kayak Fours, 1,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (72, 'Judo Men''s Heavyweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (73, 'Athletics Women''s 4 x 400 metres Relay', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (74, 'Archery Men''s Individual', 'Archery');
INSERT INTO modality (id, name, sport) VALUES (75, 'Wrestling Men''s Featherweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (76, 'Cycling Women''s Team Pursuit', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (77, 'Athletics Men''s Shot Put', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (78, 'Athletics Women''s High Jump', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (79, 'Judo Men''s Half-Middleweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (80, 'Judo Men''s Middleweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (81, 'Rowing Men''s Quadruple Sculls', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (82, 'Rowing Men''s Double Sculls', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (83, 'Water Polo Women''s Water Polo', 'Water Polo');
INSERT INTO modality (id, name, sport) VALUES (84, 'Athletics Men''s Pole Vault', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (85, 'Judo Women''s Middleweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (86, 'Judo Women''s Half-Middleweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (87, 'Sailing Women''s Two Person Dinghy', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (88, 'Wrestling Men''s Heavyweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (89, 'Swimming Men''s 100 metres Backstroke', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (90, 'Alpine Skiing Men''s Downhill', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (91, 'Alpine Skiing Men''s Giant Slalom', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (92, 'Alpine Skiing Men''s Slalom', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (93, 'Beach Volleyball Women''s Beach Volleyball', 'Beach Volleyball');
INSERT INTO modality (id, name, sport) VALUES (94, 'Tennis Men''s Singles', 'Tennis');
INSERT INTO modality (id, name, sport) VALUES (95, 'Tennis Men''s Doubles', 'Tennis');
INSERT INTO modality (id, name, sport) VALUES (96, 'Water Polo Men''s Water Polo', 'Water Polo');
INSERT INTO modality (id, name, sport) VALUES (97, 'Swimming Women''s 800 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (98, 'Swimming Women''s 400 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (99, 'Swimming Women''s 4 x 200 metres Freestyle Relay', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (100, 'Shooting Women''s Air Pistol, 10 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (101, 'Shooting Women''s Sporting Pistol, 25 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (102, 'Triathlon Men''s Olympic Distance', 'Triathlon');
INSERT INTO modality (id, name, sport) VALUES (103, 'Sailing Mixed One Person Dinghy', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (104, 'Swimming Men''s 100 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (105, 'Athletics Men''s 10 kilometres Walk', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (106, 'Sailing Mixed Skiff', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (107, 'Athletics Men''s 5,000 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (108, 'Athletics Men''s 10,000 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (109, 'Athletics Men''s Triple Jump', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (110, 'Handball Women''s Handball', 'Handball');
INSERT INTO modality (id, name, sport) VALUES (111, 'Handball Men''s Handball', 'Handball');
INSERT INTO modality (id, name, sport) VALUES (112, 'Athletics Men''s 800 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (113, 'Athletics Men''s 1,500 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (114, 'Equestrianism Mixed Jumping, Team', 'Equestrianism');
INSERT INTO modality (id, name, sport) VALUES (115, 'Cycling Men''s Sprint', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (116, 'Canoeing Men''s Kayak Singles, 500 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (117, 'Canoeing Men''s Kayak Singles, 1,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (118, 'Canoeing Men''s Kayak Doubles, 500 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (119, 'Athletics Men''s Long Jump', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (120, 'Swimming Men''s 4 x 100 metres Medley Relay', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (121, 'Swimming Men''s 100 metres Butterfly', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (122, 'Cycling Women''s BMX', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (123, 'Athletics Men''s 110 metres Hurdles', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (124, 'Canoeing Men''s Kayak Singles, 10,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (125, 'Boxing Men''s Bantamweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (126, 'Athletics Men''s 4 x 400 metres Relay', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (127, 'Rowing Men''s Lightweight Coxless Fours', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (128, 'Athletics Men''s Discus Throw', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (129, 'Shooting Women''s Trap', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (130, 'Shooting Women''s Double Trap', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (131, 'Badminton Mixed Doubles', 'Badminton');
INSERT INTO modality (id, name, sport) VALUES (132, 'Badminton Men''s Doubles', 'Badminton');
INSERT INTO modality (id, name, sport) VALUES (133, 'Diving Men''s Springboard', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (134, 'Diving Men''s Platform', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (135, 'Shooting Women''s Air Rifle, 10 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (136, 'Boxing Men''s Lightweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (137, 'Boxing Men''s Light-Middleweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (138, 'Weightlifting Men''s Lightweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (139, 'Bobsleigh Men''s Four', 'Bobsleigh');
INSERT INTO modality (id, name, sport) VALUES (140, 'Bobsleigh Men''s Two', 'Bobsleigh');
INSERT INTO modality (id, name, sport) VALUES (141, 'Canoeing Women''s Kayak Fours, 500 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (142, 'Equestrianism Men''s Three-Day Event, Individual', 'Equestrianism');
INSERT INTO modality (id, name, sport) VALUES (143, 'Equestrianism Men''s Three-Day Event, Team', 'Equestrianism');
INSERT INTO modality (id, name, sport) VALUES (144, 'Weightlifting Women''s Lightweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (145, 'Athletics Men''s 100 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (146, 'Athletics Men''s 400 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (147, 'Archery Men''s Team', 'Archery');
INSERT INTO modality (id, name, sport) VALUES (148, 'Swimming Women''s 100 metres Breaststroke', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (149, 'Swimming Women''s 200 metres Breaststroke', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (150, 'Diving Women''s Springboard', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (151, 'Diving Men''s Synchronized Springboard', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (152, 'Volleyball Women''s Volleyball', 'Volleyball');
INSERT INTO modality (id, name, sport) VALUES (153, 'Swimming Women''s 200 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (154, 'Modern Pentathlon Men''s Individual', 'Modern Pentathlon');
INSERT INTO modality (id, name, sport) VALUES (155, 'Wrestling Men''s Bantamweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (156, 'Taekwondo Women''s Welterweight', 'Taekwondo');
INSERT INTO modality (id, name, sport) VALUES (157, 'Fencing Men''s Foil, Individual', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (158, 'Boxing Men''s Flyweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (159, 'Cycling Women''s Individual Pursuit, 3,000 metres', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (160, 'Cycling Women''s Points Race', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (161, 'Cycling Women''s Road Race, Individual', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (162, 'Basketball Women''s Basketball', 'Basketball');
INSERT INTO modality (id, name, sport) VALUES (163, 'Rowing Men''s Coxless Pairs', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (164, 'Weightlifting Men''s Middleweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (165, 'Swimming Women''s 100 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (166, 'Fencing Women''s Foil, Individual', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (167, 'Cycling Men''s Keirin', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (168, 'Cycling Men''s Team Sprint', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (169, 'Cycling Women''s Mountainbike, Cross-Country', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (170, 'Boxing Men''s Super-Heavyweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (171, 'Alpine Skiing Men''s Super G', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (172, 'Alpine Skiing Men''s Combined', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (173, 'Sailing Men''s Two Person Keelboat', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (174, 'Diving Women''s Plain High', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (175, 'Swimming Women''s 300 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (176, 'Swimming Men''s 200 metres Backstroke', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (177, 'Rugby Sevens Women''s Rugby Sevens', 'Rugby Sevens');
INSERT INTO modality (id, name, sport) VALUES (178, 'Athletics Men''s 400 metres Hurdles', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (179, 'Swimming Women''s 100 metres Backstroke', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (180, 'Freestyle Skiing Men''s Moguls', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (181, 'Sailing Men''s Two Person Dinghy', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (182, 'Swimming Women''s 4 x 100 metres Freestyle Relay', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (183, 'Canoeing Men''s Canadian Singles, Slalom', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (184, 'Cross Country Skiing Men''s Sprint', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (185, 'Cross Country Skiing Men''s Team Sprint', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (186, 'Canoeing Men''s Canadian Doubles, Slalom', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (187, 'Rowing Men''s Lightweight Double Sculls', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (188, 'Athletics Women''s 200 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (189, 'Athletics Women''s 4 x 100 metres Relay', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (190, 'Equestrianism Mixed Three-Day Event, Individual', 'Equestrianism');
INSERT INTO modality (id, name, sport) VALUES (191, 'Equestrianism Mixed Three-Day Event, Team', 'Equestrianism');
INSERT INTO modality (id, name, sport) VALUES (192, 'Judo Men''s Lightweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (193, 'Freestyle Skiing Women''s Moguls', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (194, 'Equestrianism Mixed Dressage, Individual', 'Equestrianism');
INSERT INTO modality (id, name, sport) VALUES (195, 'Equestrianism Mixed Dressage, Team', 'Equestrianism');
INSERT INTO modality (id, name, sport) VALUES (196, 'Swimming Men''s 200 metres Breaststroke', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (197, 'Swimming Men''s 200 metres Individual Medley', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (198, 'Swimming Men''s 200 metres Butterfly', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (199, 'Sailing Mixed 5.5 metres', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (200, 'Canoeing Men''s Kayak Doubles, 200 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (201, 'Canoeing Men''s Kayak Singles, 200 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (202, 'Boxing Men''s Featherweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (203, 'Gymnastics Men''s Individual All-Around', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (204, 'Gymnastics Men''s Floor Exercise', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (205, 'Gymnastics Men''s Horse Vault', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (206, 'Gymnastics Men''s Parallel Bars', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (207, 'Gymnastics Men''s Horizontal Bar', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (208, 'Gymnastics Men''s Rings', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (209, 'Gymnastics Men''s Pommelled Horse', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (210, 'Table Tennis Women''s Singles', 'Table Tennis');
INSERT INTO modality (id, name, sport) VALUES (211, 'Table Tennis Women''s Doubles', 'Table Tennis');
INSERT INTO modality (id, name, sport) VALUES (212, 'Athletics Women''s 100 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (213, 'Gymnastics Men''s Team All-Around', 'Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (214, 'Rhythmic Gymnastics Women''s Individual', 'Rhythmic Gymnastics');
INSERT INTO modality (id, name, sport) VALUES (215, 'Athletics Men''s 5 mile', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (216, 'Sailing Women''s One Person Dinghy', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (217, 'Canoeing Women''s Kayak Singles, 500 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (218, 'Athletics Women''s 10 kilometres Walk', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (219, 'Short Track Speed Skating Men''s 500 metres', 'Short Track Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (220, 'Athletics Women''s 400 metres Hurdles', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (221, 'Athletics Women''s Long Jump', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (222, 'Snowboarding Men''s Boardercross', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (223, 'Cross Country Skiing Women''s 5 kilometres', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (224, 'Cross Country Skiing Women''s 10 kilometres', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (225, 'Canoeing Women''s Kayak Doubles, 500 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (226, 'Short Track Speed Skating Women''s 500 metres', 'Short Track Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (227, 'Short Track Speed Skating Women''s 1,000 metres', 'Short Track Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (228, 'Short Track Speed Skating Women''s 1,500 metres', 'Short Track Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (229, 'Judo Men''s Open Class', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (230, 'Cross Country Skiing Women''s Sprint', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (231, 'Sailing Men''s One Person Dinghy', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (232, 'Cycling Men''s Mountainbike, Cross-Country', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (233, 'Figure Skating Mixed Pairs', 'Figure Skating');
INSERT INTO modality (id, name, sport) VALUES (234, 'Boxing Men''s Welterweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (235, 'Athletics Women''s Pole Vault', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (236, 'Skeleton Men''s Skeleton', 'Skeleton');
INSERT INTO modality (id, name, sport) VALUES (237, 'Short Track Speed Skating Men''s 1,000 metres', 'Short Track Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (238, 'Short Track Speed Skating Men''s 5,000 metres Relay', 'Short Track Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (239, 'Short Track Speed Skating Men''s 1,500 metres', 'Short Track Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (240, 'Rowing Women''s Quadruple Sculls', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (241, 'Rowing Women''s Coxed Fours', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (242, 'Athletics Women''s Shot Put', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (243, 'Badminton Men''s Singles', 'Badminton');
INSERT INTO modality (id, name, sport) VALUES (244, 'Wrestling Women''s Flyweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (245, 'Archery Women''s Team', 'Archery');
INSERT INTO modality (id, name, sport) VALUES (246, 'Alpine Skiing Women''s Combined', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (247, 'Snowboarding Women''s Halfpipe', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (248, 'Snowboarding Women''s Slopestyle', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (249, 'Snowboarding Women''s Boardercross', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (250, 'Athletics Men''s 200 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (251, 'Cycling Men''s 50 kilometres', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (252, 'Shooting Mixed Small-Bore Rifle, Prone, 50 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (253, 'Shooting Mixed Small-Bore Rifle, Three Positions, 50 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (254, 'Shooting Men''s Small-Bore Rifle, Three Positions, 50 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (255, 'Shooting Men''s Small-Bore Rifle, Prone, 50 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (256, 'Figure Skating Women''s Singles', 'Figure Skating');
INSERT INTO modality (id, name, sport) VALUES (257, 'Wrestling Men''s Lightweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (258, 'Sailing Mixed Two Person Dinghy', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (259, 'Judo Men''s Half-Lightweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (260, 'Table Tennis Men''s Singles', 'Table Tennis');
INSERT INTO modality (id, name, sport) VALUES (261, 'Table Tennis Men''s Doubles', 'Table Tennis');
INSERT INTO modality (id, name, sport) VALUES (262, 'Canoeing Men''s Kayak Doubles, 1,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (263, 'Canoeing Men''s Kayak Doubles, 10,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (264, 'Cycling Men''s Tandem Sprint, 2,000 metres', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (265, 'Athletics Men''s Decathlon', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (266, 'Cross Country Skiing Women''s 15 km Skiathlon', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (267, 'Shooting Men''s Trap', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (268, 'Fencing Men''s Foil, Team', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (269, 'Diving Women''s Synchronized Platform', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (270, 'Boxing Men''s Middleweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (271, 'Rowing Men''s Single Sculls', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (272, 'Shooting Men''s Air Rifle, 10 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (273, 'Judo Women''s Heavyweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (274, 'Taekwondo Women''s Flyweight', 'Taekwondo');
INSERT INTO modality (id, name, sport) VALUES (275, 'Cycling Men''s Points Race', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (276, 'Synchronized Swimming Women''s Solo', 'Synchronized Swimming');
INSERT INTO modality (id, name, sport) VALUES (277, 'Cycling Men''s Individual Pursuit, 4,000 metres', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (278, 'Tennis Women''s Singles', 'Tennis');
INSERT INTO modality (id, name, sport) VALUES (279, 'Wrestling Men''s Featherweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (280, 'Swimming Women''s 200 metres Individual Medley', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (281, 'Athletics Women''s 80 metres Hurdles', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (282, 'Athletics Women''s 100 metres Hurdles', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (283, 'Taekwondo Women''s Featherweight', 'Taekwondo');
INSERT INTO modality (id, name, sport) VALUES (284, 'Swimming Women''s 50 metres Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (285, 'Rowing Women''s Double Sculls', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (286, 'Badminton Women''s Singles', 'Badminton');
INSERT INTO modality (id, name, sport) VALUES (287, 'Luge Women''s Singles', 'Luge');
INSERT INTO modality (id, name, sport) VALUES (288, 'Freestyle Skiing Women''s Aerials', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (289, 'Weightlifting Men''s Bantamweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (290, 'Weightlifting Men''s Featherweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (291, 'Athletics Men''s Hammer Throw', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (292, 'Boxing Men''s Light-Welterweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (293, 'Taekwondo Men''s Flyweight', 'Taekwondo');
INSERT INTO modality (id, name, sport) VALUES (294, 'Figure Skating Men''s Singles', 'Figure Skating');
INSERT INTO modality (id, name, sport) VALUES (295, 'Swimming Women''s 400 metres Individual Medley', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (296, 'Athletics Women''s Marathon', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (297, 'Sailing Men''s One Person Heavyweight Dinghy', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (298, 'Boxing Men''s Light-Heavyweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (299, 'Badminton Women''s Doubles', 'Badminton');
INSERT INTO modality (id, name, sport) VALUES (300, 'Cycling Men''s Road Race, Team', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (301, 'Judo Men''s Half-Heavyweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (302, 'Skeleton Women''s Skeleton', 'Skeleton');
INSERT INTO modality (id, name, sport) VALUES (303, 'Weightlifting Men''s Light-Heavyweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (304, 'Shooting Men''s Rapid-Fire Pistol, 25 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (305, 'Cycling Men''s 1,000 metres Time Trial', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (306, 'Judo Women''s Extra-Lightweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (307, 'Modern Pentathlon Women''s Individual', 'Modern Pentathlon');
INSERT INTO modality (id, name, sport) VALUES (308, 'Judo Men''s Extra-Lightweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (309, 'Weightlifting Men''s Middle-Heavyweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (310, 'Rugby Sevens Men''s Rugby Sevens', 'Rugby Sevens');
INSERT INTO modality (id, name, sport) VALUES (311, 'Figure Skating Mixed Ice Dancing', 'Figure Skating');
INSERT INTO modality (id, name, sport) VALUES (312, 'Speed Skating Men''s 500 metres', 'Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (313, 'Speed Skating Men''s 1,500 metres', 'Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (314, 'Speed Skating Men''s 5,000 metres', 'Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (315, 'Speed Skating Men''s 10,000 metres', 'Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (316, 'Speed Skating Men''s 1,000 metres', 'Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (317, 'Rowing Men''s Coxed Pairs', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (318, 'Diving Women''s Synchronized Springboard', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (319, 'Canoeing Men''s Kayak Relay 4 x 500 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (320, 'Rowing Women''s Coxless Pairs', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (321, 'Modern Pentathlon Men''s Team', 'Modern Pentathlon');
INSERT INTO modality (id, name, sport) VALUES (322, 'Wrestling Men''s Light-Heavyweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (323, 'Rowing Women''s Single Sculls', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (324, 'Athletics Women''s Discus Throw', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (325, 'Freestyle Skiing Women''s Ski Cross', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (326, 'Shooting Mixed Skeet', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (327, 'Sailing Women''s Windsurfer', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (328, 'Sailing Women''s Three Person Keelboat', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (329, 'Trampolining Women''s Individual', 'Trampolining');
INSERT INTO modality (id, name, sport) VALUES (330, 'Table Tennis Men''s Team', 'Table Tennis');
INSERT INTO modality (id, name, sport) VALUES (331, 'Alpine Skiing Women''s Downhill', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (332, 'Cycling Men''s BMX', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (333, 'Canoeing Men''s Kayak Singles, Slalom', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (334, 'Tennis Women''s Doubles', 'Tennis');
INSERT INTO modality (id, name, sport) VALUES (335, 'Cycling Men''s Individual Time Trial', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (336, 'Triathlon Women''s Olympic Distance', 'Triathlon');
INSERT INTO modality (id, name, sport) VALUES (337, 'Shooting Mixed Trap', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (338, 'Shooting Men''s Double Trap', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (339, 'Rowing Women''s Coxless Fours', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (340, 'Canoeing Men''s Canadian Singles, 1,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (341, 'Canoeing Men''s Canadian Doubles, 1,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (342, 'Boxing Men''s Light-Flyweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (343, 'Shooting Mixed Free Pistol, 50 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (344, 'Athletics Men''s Pentathlon', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (345, 'Athletics Women''s Hammer Throw', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (346, 'Weightlifting Men''s Super-Heavyweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (347, 'Cycling Women''s Omnium', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (348, 'Cross Country Skiing Men''s 10 kilometres', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (349, 'Cross Country Skiing Men''s 10/15 kilometres Pursuit', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (350, 'Swimming Men''s 100 metres Breaststroke', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (351, 'Diving Men''s Plain High', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (352, 'Rowing Women''s Lightweight Double Sculls', 'Rowing');
INSERT INTO modality (id, name, sport) VALUES (353, 'Fencing Men''s Sabre, Individual', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (354, 'Fencing Men''s Sabre, Team', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (355, 'Canoeing Women''s Kayak Singles, Slalom', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (356, 'Athletics Women''s 10,000 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (357, 'Shooting Women''s Small-Bore Rifle, Three Positions, 50 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (358, 'Luge Men''s Singles', 'Luge');
INSERT INTO modality (id, name, sport) VALUES (359, 'Cycling Women''s Sprint', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (360, 'Cycling Women''s 500 metres Time Trial', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (361, 'Alpinism Mixed Alpinism', 'Alpinism');
INSERT INTO modality (id, name, sport) VALUES (362, 'Boxing Women''s Middleweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (363, 'Boxing Men''s Heavyweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (364, 'Wrestling Men''s Flyweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (365, 'Athletics Women''s Heptathlon', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (366, 'Swimming Women''s 200 metres Butterfly', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (367, 'Golf Men''s Individual', 'Golf');
INSERT INTO modality (id, name, sport) VALUES (368, 'Athletics Women''s Pentathlon', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (369, 'Swimming Men''s 220 yard Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (370, 'Swimming Men''s 440 yard Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (371, 'Swimming Men''s 880 yard Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (372, 'Swimming Men''s One Mile Freestyle', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (373, 'Judo Women''s Half-Heavyweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (374, 'Cycling Women''s Individual Time Trial', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (375, 'Trampolining Men''s Individual', 'Trampolining');
INSERT INTO modality (id, name, sport) VALUES (376, 'Shooting Men''s Running Target, 10 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (377, 'Biathlon Women''s 7.5 kilometres Sprint', 'Biathlon');
INSERT INTO modality (id, name, sport) VALUES (378, 'Biathlon Women''s 15 kilometres', 'Biathlon');
INSERT INTO modality (id, name, sport) VALUES (379, 'Shooting Men''s Free Rifle, Three Positions, 300 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (380, 'Swimming Women''s 10 kilometres Open Water', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (381, 'Athletics Women''s 3,000 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (382, 'Judo Women''s Half-Lightweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (383, 'Freestyle Skiing Men''s Ski Cross', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (384, 'Beach Volleyball Men''s Beach Volleyball', 'Beach Volleyball');
INSERT INTO modality (id, name, sport) VALUES (385, 'Wrestling Men''s Flyweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (386, 'Fencing Women''s epee, Individual', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (387, 'Taekwondo Men''s Welterweight', 'Taekwondo');
INSERT INTO modality (id, name, sport) VALUES (388, 'Canoeing Men''s Canadian Singles, 10,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (389, 'Taekwondo Men''s Featherweight', 'Taekwondo');
INSERT INTO modality (id, name, sport) VALUES (390, 'Cross Country Skiing Men''s 18 kilometres', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (391, 'Weightlifting Men''s Flyweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (392, 'Athletics Women''s Javelin Throw', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (393, 'Diving Men''s Synchronized Platform', 'Diving');
INSERT INTO modality (id, name, sport) VALUES (394, 'Freestyle Skiing Men''s Slopestyle', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (395, 'Tennis Mixed Doubles', 'Tennis');
INSERT INTO modality (id, name, sport) VALUES (396, 'Judo Women''s Lightweight', 'Judo');
INSERT INTO modality (id, name, sport) VALUES (397, 'Athletics Women''s 3,000 metres Steeplechase', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (398, 'Athletics Women''s 20 kilometres Walk', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (399, 'Fencing Women''s Foil, Team', 'Fencing');
INSERT INTO modality (id, name, sport) VALUES (400, 'Wrestling Men''s Middleweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (401, 'Swimming Men''s 10 kilometres Open Water', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (402, 'Sailing Men''s Windsurfer', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (403, 'Snowboarding Men''s Slopestyle', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (404, 'Sailing Men''s Skiff', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (405, 'Shooting Women''s Skeet', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (406, 'Alpine Skiing Women''s Super G', 'Alpine Skiing');
INSERT INTO modality (id, name, sport) VALUES (407, 'Canoeing Men''s Canadian Doubles, 10,000 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (408, 'Weightlifting Women''s Light-Heavyweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (409, 'Wrestling Men''s Super-Heavyweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (410, 'Canoeing Men''s Canadian Singles, 500 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (411, 'Swimming Men''s 200 metres Obstacle Course', 'Swimming');
INSERT INTO modality (id, name, sport) VALUES (412, 'Sailing Mixed Windsurfer', 'Sailing');
INSERT INTO modality (id, name, sport) VALUES (413, 'Table Tennis Women''s Team', 'Table Tennis');
INSERT INTO modality (id, name, sport) VALUES (414, 'Golf Women''s Individual', 'Golf');
INSERT INTO modality (id, name, sport) VALUES (415, 'Weightlifting Women''s Middleweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (416, 'Bobsleigh Women''s Two', 'Bobsleigh');
INSERT INTO modality (id, name, sport) VALUES (417, 'Weightlifting Women''s Heavyweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (418, 'Weightlifting Women''s Super-Heavyweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (419, 'Wrestling Men''s Light-Heavyweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (420, 'Weightlifting Men''s Heavyweight', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (421, 'Canoeing Men''s Canadian Singles, 200 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (422, 'Taekwondo Women''s Heavyweight', 'Taekwondo');
INSERT INTO modality (id, name, sport) VALUES (423, 'Cycling Women''s Team Sprint', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (424, 'Cycling Women''s Keirin', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (425, 'Weightlifting Men''s Heavyweight II', 'Weightlifting');
INSERT INTO modality (id, name, sport) VALUES (426, 'Freestyle Skiing Men''s Aerials', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (427, 'Speed Skating Women''s 500 metres', 'Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (428, 'Speed Skating Women''s 1,000 metres', 'Speed Skating');
INSERT INTO modality (id, name, sport) VALUES (429, 'Nordic Combined Men''s Individual', 'Nordic Combined');
INSERT INTO modality (id, name, sport) VALUES (430, 'Canoeing Women''s Kayak Singles, 200 metres', 'Canoeing');
INSERT INTO modality (id, name, sport) VALUES (431, 'Snowboarding Men''s Parallel Giant Slalom', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (432, 'Cycling Men''s Omnium', 'Cycling');
INSERT INTO modality (id, name, sport) VALUES (433, 'Athletics Men''s 3,000 metres Walk', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (434, 'Wrestling Men''s Super-Heavyweight, Freestyle', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (435, 'Art Competitions Mixed Painting, Unknown Event', 'Art Competitions');
INSERT INTO modality (id, name, sport) VALUES (436, 'Art Competitions Mixed Music', 'Art Competitions');
INSERT INTO modality (id, name, sport) VALUES (437, 'Athletics Men''s 60 metres', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (438, 'Athletics Men''s 5,000 metres, Team', 'Athletics');
INSERT INTO modality (id, name, sport) VALUES (439, 'Freestyle Skiing Women''s Slopestyle', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (440, 'Snowboarding Women''s Parallel Giant Slalom', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (441, 'Freestyle Skiing Women''s Halfpipe', 'Freestyle Skiing');
INSERT INTO modality (id, name, sport) VALUES (442, 'Cross Country Skiing Men''s 30 km Skiathlon', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (443, 'Wrestling Men''s Lightweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (444, 'Snowboarding Men''s Giant Slalom', 'Snowboarding');
INSERT INTO modality (id, name, sport) VALUES (445, 'Wrestling Men''s Bantamweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (446, 'Shooting Mixed Rapid-Fire Pistol, 25 metres', 'Shooting');
INSERT INTO modality (id, name, sport) VALUES (447, 'Taekwondo Men''s Heavyweight', 'Taekwondo');
INSERT INTO modality (id, name, sport) VALUES (448, 'Wrestling Men''s Heavyweight, Greco-Roman', 'Wrestling');
INSERT INTO modality (id, name, sport) VALUES (449, 'Cross Country Skiing Women''s 30 kilometres', 'Cross Country Skiing');
INSERT INTO modality (id, name, sport) VALUES (450, 'Boxing Women''s Lightweight', 'Boxing');
INSERT INTO modality (id, name, sport) VALUES (451, 'Shooting Men''s Running Target, 50 metres', 'Shooting');
INSERT INTO modality (id, name) VALUES (452, 'Slalom, Men');
INSERT INTO modality (id, name) VALUES (453, 'Middleweight, Freestyle, Women');
INSERT INTO modality (id, name) VALUES (454, 'Lightweight, Freestyle, Women');
INSERT INTO modality (id, name) VALUES (455, 'Featherweight, Freestyle, Women');
INSERT INTO modality (id, name) VALUES (456, 'Individual, Men');
INSERT INTO modality (id, name) VALUES (457, 'Team, Men');
