INSERT INTO olympic (id, year, season, city, name) VALUES (1, 2008, 'Summer', 'Beijing', '2008 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (2, 2012, 'Summer', 'London', '2012 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (3, 2000, 'Summer', 'Sydney', '2000 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (4, 2004, 'Summer', 'Athina', '2004 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (5, 2016, 'Summer', 'Rio de Janeiro', '2016 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (6, 1956, 'Summer', 'Melbourne', '1956 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (7, 1960, 'Winter', 'Squaw Valley', '1960 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (8, 1992, 'Summer', 'Barcelona', '1992 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (9, 1976, 'Summer', 'Montreal', '1976 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (10, 1984, 'Summer', 'Los Angeles', '1984 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (11, 1988, 'Summer', 'Seoul', '1988 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (12, 1996, 'Summer', 'Atlanta', '1996 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (13, 1948, 'Summer', 'London', '1948 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (14, 1952, 'Summer', 'Helsinki', '1952 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (15, 1964, 'Summer', 'Tokyo', '1964 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (16, 1972, 'Summer', 'Munich', '1972 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (17, 1980, 'Summer', 'Moskva', '1980 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (18, 2006, 'Winter', 'Torino', '2006 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (19, 1984, 'Winter', 'Sarajevo', '1984 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (20, 1960, 'Summer', 'Roma', '1960 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (21, 2010, 'Winter', 'Vancouver', '2010 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (22, 2014, 'Winter', 'Sochi', '2014 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (23, 1980, 'Winter', 'Lake Placid', '1980 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (24, 1968, 'Summer', 'Mexico City', '1968 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (25, 1924, 'Summer', 'Paris', '1924 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (26, 1952, 'Winter', 'Oslo', '1952 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (27, 1956, 'Winter', 'Cortina d''Ampezzo', '1956 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (28, 1936, 'Summer', 'Berlin', '1936 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (29, 1994, 'Winter', 'Lillehammer', '1994 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (30, 1998, 'Winter', 'Nagano', '1998 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (31, 1956, 'Summer', 'Stockholm', '1956 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (32, 1906, 'Summer', 'Athina', '1906 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (33, 1932, 'Summer', 'Los Angeles', '1932 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (34, 2002, 'Winter', 'Salt Lake City', '2002 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (35, 1920, 'Summer', 'Antwerpen', '1920 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (36, 1988, 'Winter', 'Calgary', '1988 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (37, 1928, 'Summer', 'Amsterdam', '1928 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (38, 1964, 'Winter', 'Innsbruck', '1964 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (39, 1976, 'Winter', 'Innsbruck', '1976 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (40, 1992, 'Winter', 'Albertville', '1992 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (41, 1972, 'Winter', 'Sapporo', '1972 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (42, 1968, 'Winter', 'Grenoble', '1968 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (43, 1924, 'Winter', 'Chamonix', '1924 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (44, 1896, 'Summer', 'Athina', '1896 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (45, 1904, 'Summer', 'St. Louis', '1904 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (46, 1936, 'Winter', 'Garmisch-Partenkirchen', '1936 Winter');
INSERT INTO olympic (id, year, season, city, name) VALUES (47, 1900, 'Summer', 'Paris', '1900 Summer');
INSERT INTO olympic (id, year, season, city, name) VALUES (48, 2020, 'Summer', '', '2020 Summer');
